<?php

/**
 * @file
 * Testbed Module.
 */

/**
 * Implements hook_menu().
 */
function testbed_menu() {
  $items['test'] = array(
    'title' => 'Test',
    'page callback' => 'testbed_test',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Log a variable to watchdog.
 *
 * @param mixed $var
 *   The variable to log.
 * @param string $label
 *   (Optional) The label to use for the watchdog entry. Defaults to "Testbed".
 */
function testbed_log($var, $label = 'Testbed') {
  if (module_exists('devel')) {
    dfb($var);
  }

  watchdog($label, '<pre>!dump</pre>', array('!dump' => print_r($var, TRUE)));
}

/**
 * Callback function for Testbed.
 *
 * To use this function go to /test/<function_to_test>
 *
 * To pass arguments to the function you are testing, provide them as
 * additional path arguments.
 *
 * E.G. To test loading Node 123 with node_load, go to /test/node_load/123
 *
 * At present, only scalar arguments are supported (i.e. Strings and
 * Integers). Even then, strings with spaces are problematic, as the URL will
 * translate the spaces to the %20 placeholder. Be aware of this.
 */
function testbed_test() {
  $args = func_get_args();

  if (count($args) < 1) {
    drupal_set_message(t('Please specify a function to test.'), 'error');
    return 'Fail';
  }

  $function = array_shift($args);

  // @todo Sanitize inputs!

  if (function_exists($function)) {
    $result = call_user_func_array($function, $args);
    drupal_set_message(t('Ran Function @function', ['@function' => $function]));

    if (is_array($result) || is_object($result)) {
      if (module_exists('devel')) {
        dpm($result);
      }
      else {
        drupal_set_message(sprinf('<pre>%s</pre>', print_r($result, TRUE)));
      }

      return 'Success';
    }

    if (is_string($result)) {
      return $result;
    }

    return sprintf('Result: %d', $result);
  }
  else {
    drupal_set_message(t("Undefined function @function", ['@function' => $function]), 'error');
    return 'Fail';
  }

}

/**
 * Sample Testbed Function.
 *
 * To run this function go to /test/testbed_sample.
 */
function testbed_sample() {
  return func_get_args();
}
